[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault_q2_2026 = "FZ6rfnsv1AojeU9kVLsrUNbSSRpWhcHDMKMXtq47p3We"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
